version: "3.3"
name: shapes-app
services:
    # PHP service
    app:
        build: .
        container_name: shapes_app
        working_dir: "/var/www"
        volumes:
            - ../:/var/www
            - ./docker-php-custom.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
        networks:
            - app-network-1120
    
    db_app:
        image: postgres:15
        container_name: shapes_db
        ports:
            - '5441:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - './db:/var/lib/postgresql/data'
        networks:
            - app-network-1120
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: shapes_nginx
        ports:
            - 8023:80
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network-1120

networks:
    app-network-1120:
        driver: bridge
